-- MySQL Script generated by MySQL Workbench
-- Thu May 11 21:36:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- АЛЕКСАНДР ГЕННАДЬЕВИЧ! Пароль от базы данных: 123

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema zyryanov_bookshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zyryanov_bookshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zyryanov_bookshop` DEFAULT CHARACTER SET utf8 ;
USE `zyryanov_bookshop` ;

-- -----------------------------------------------------
-- Table `zyryanov_bookshop`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zyryanov_bookshop`.`Books` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `BookTitle` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(1000) NULL DEFAULT NULL,
  `Author` VARCHAR(45) NOT NULL,
  `Price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zyryanov_bookshop`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zyryanov_bookshop`.`Roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Role` VARCHAR(100) NULL DEFAULT '2',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zyryanov_bookshop`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zyryanov_bookshop`.`Users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `fk_Roles` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Roles(sql)_idx` (`fk_Roles` ASC),
  CONSTRAINT `fk_Roles(sql)`
    FOREIGN KEY (`fk_Roles`)
    REFERENCES `zyryanov_bookshop`.`Roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zyryanov_bookshop`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zyryanov_bookshop`.`Orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_Book` INT(11) NOT NULL,
  `fk_Users` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users` (`fk_Users` ASC),
  INDEX `fk_Book_idx` (`fk_Book` ASC),
  CONSTRAINT `fk_Book`
    FOREIGN KEY (`fk_Book`)
    REFERENCES `zyryanov_bookshop`.`Books` (`id`),
  CONSTRAINT `fk_Users`
    FOREIGN KEY (`fk_Users`)
    REFERENCES `zyryanov_bookshop`.`Users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
