//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 03:21:10 PM MSK 
//


package by.it.loktev.jd02_09;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Circle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Circle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="centerx" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="centery" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="radius" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="fill" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="stroke" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Circle")
public class Circle {

    @XmlAttribute(name = "centerx", required = true)
    protected int centerx;
    @XmlAttribute(name = "centery", required = true)
    protected int centery;
    @XmlAttribute(name = "radius", required = true)
    protected int radius;
    @XmlAttribute(name = "fill")
    protected String fill;
    @XmlAttribute(name = "stroke")
    protected String stroke;

    public Circle() {
        centerx=0;
        centery=0;
        radius=100;
        fill="none";
        stroke="black";
    }

    /**
     * Gets the value of the centerx property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getCenterx() {
        return centerx;
    }

    /**
     * Sets the value of the centerx property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setCenterx(int value) {
        this.centerx = value;
    }

    /**
     * Gets the value of the centery property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getCentery() {
        return centery;
    }

    /**
     * Sets the value of the centery property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setCentery(int value) {
        this.centery = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setRadius(int value) {
        this.radius = value;
    }

    /**
     * Gets the value of the fill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFill(String value) {
        this.fill = value;
    }

    /**
     * Gets the value of the stroke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStroke() {
        return stroke;
    }

    /**
     * Sets the value of the stroke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStroke(String value) {
        this.stroke = value;
    }

    @Override
    public String toString() {
        return "Circle " +
                "centerx=" + centerx +
                " centery=" + centery +
                " radius=" + radius +
                " fill=" + fill +
                " stroke=" + stroke
                ;
    }

}
