//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 07:57:54 PM EET 
//


package by.it.sorokoee.jd02_09;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ad">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Car" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="YearOfIssue" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TypeEngine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CapacityEngine" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Spares" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ad", propOrder = {

})
public class Ad {

    @XmlElement(name = "Car", required = true)
    protected String car;
    @XmlElement(name = "YearOfIssue", required = true)
    protected BigInteger yearOfIssue;
    @XmlElement(name = "TypeEngine", required = true)
    protected String typeEngine;
    @XmlElement(name = "CapacityEngine")
    protected double capacityEngine;
    @XmlElement(name = "Spares", required = true)
    protected String spares;

    /**
     * Gets the value of the car property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCar() {
        return car;
    }

    /**
     * Sets the value of the car property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCar(String value) {
        this.car = value;
    }

    /**
     * Gets the value of the yearOfIssue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getYearOfIssue() {
        return yearOfIssue;
    }

    /**
     * Sets the value of the yearOfIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setYearOfIssue(BigInteger value) {
        this.yearOfIssue = value;
    }

    /**
     * Gets the value of the typeEngine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeEngine() {
        return typeEngine;
    }

    /**
     * Sets the value of the typeEngine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeEngine(String value) {
        this.typeEngine = value;
    }

    /**
     * Gets the value of the capacityEngine property.
     * 
     */
    public double getCapacityEngine() {
        return capacityEngine;
    }

    /**
     * Sets the value of the capacityEngine property.
     * 
     */
    public void setCapacityEngine(double value) {
        this.capacityEngine = value;
    }

    /**
     * Gets the value of the spares property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpares() {
        return spares;
    }

    /**
     * Sets the value of the spares property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpares(String value) {
        this.spares = value;
    }

    @Override
    public String toString() {
        return "Ad{" +
                "\ncar='" + car + '\'' +
                "\n, yearOfIssue=" + yearOfIssue +
                "\n, typeEngine='" + typeEngine + '\'' +
                "\n, capacityEngine=" + capacityEngine +
                "\n, spares='" + spares + '\'' +
                "\n}";
    }
}
