//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 08:45:19 PM MSK 
//


package by.it.smirnov.jd02_09.task_b.beans;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Banks" type="{http://task_b.jd02_09.smirnov.it.by/}Banks" maxOccurs="unbounded"/>
 *         &lt;element name="Limits" type="{http://task_b.jd02_09.smirnov.it.by/}Limits" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "banks",
    "limits"
})
@XmlRootElement(name = "BankLimits")
public class BankLimits {

    @XmlElement(name = "Banks", required = true)
    protected List<Banks> banks;
    @XmlElement(name = "Limits", required = true)
    protected List<Limits> limits;

    /**
     * Gets the value of the banks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the banks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBanks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Banks }
     * 
     * 
     */
    public List<Banks> getBanks() {
        if (banks == null) {
            banks = new ArrayList<Banks>();
        }
        return this.banks;
    }

    /**
     * Gets the value of the limits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the limits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLimits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Limits }
     * 
     * 
     */
    public List<Limits> getLimits() {
        if (limits == null) {
            limits = new ArrayList<Limits>();
        }
        return this.limits;
    }

    public BankLimits() {
    }

    @Override
    public String toString() {
        return "BankLimits{" +
                "banks=" + banks +
                ", limits=" + limits +
                '}';
    }
}
