//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 08:45:19 PM MSK 
//


package by.it.smirnov.jd02_09.task_b.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it.smirnov.jd02_09.task_b package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.smirnov.jd02_09.task_b
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BankLimits }
     *
     */
    public BankLimits createBankLimits() {
        return new BankLimits();
    }

    /**
     * Create an instance of {@link Banks }
     *
     */
    public Banks createBanks() {
        return new Banks();
    }

    /**
     * Create an instance of {@link Limits }
     *
     */
    public Limits createLimits() {
        return new Limits();
    }

    /**
     * Create an instance of {@link Lim }
     * 
     */
    public Lim createLim() {
        return new Lim();
    }

    /**
     * Create an instance of {@link Bank }
     * 
     */
    public Bank createBank() {
        return new Bank();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Opers }
     * 
     */
    public Opers createOpers() {
        return new Opers();
    }

    /**
     * Create an instance of {@link Limit }
     * 
     */
    public Limit createLimit() {
        return new Limit();
    }

    /**
     * Create an instance of {@link Oper }
     * 
     */
    public Oper createOper() {
        return new Oper();
    }

}
