//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 08:45:19 PM MSK 
//


package by.it.smirnov.jd02_10.task_c.pojo_class;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Oper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Oper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Summa" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Valut" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://pojo_class.task_b.jd02_10.smirnov.it.by/}TypeOper" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Oper", propOrder = {
    "summa",
    "valut"
})
public class Oper {

    @XmlElement(name = "Summa")
    protected float summa;
    @XmlElement(name = "Valut", required = true)
    protected String valut;
    @XmlAttribute(name = "type", required = true)
    protected TypeOper type;

    /**
     * Gets the value of the summa property.
     *
     */
    public float getSumma() {
        return summa;
    }

    /**
     * Sets the value of the summa property.
     *
     */
    public void setSumma(float value) {
        this.summa = value;
    }

    /**
     * Gets the value of the valut property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValut() {
        return valut;
    }

    /**
     * Sets the value of the valut property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValut(String value) {
        this.valut = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link TypeOper }
     *
     */
    public TypeOper getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link TypeOper }
     *
     */
    public void setType(TypeOper value) {
        this.type = value;
    }

    public Oper() {}

    @Override
    public String toString() {
        return "Oper{" +
                "summa=" + summa +
                ", valut='" + valut + '\'' +
                ", type=" + type +
                '}';
    }
}
