//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 12:19:33 PM MSK 
//


package by.it.loktev.jd02_09a;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="square" type="{http://jd02_09a.loktev.it.by}TSquare"/>
 *         &lt;element name="circle" type="{http://jd02_09a.loktev.it.by}TCircle"/>
 *         &lt;element name="text" type="{http://jd02_09a.loktev.it.by}TText"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "squareOrCircleOrText"
})
@XmlRootElement(name = "group")
public class Group {

    @XmlElements({
        @XmlElement(name = "square", type = TSquare.class),
        @XmlElement(name = "circle", type = TCircle.class),
        @XmlElement(name = "text", type = TText.class)
    })
    protected List<Object> squareOrCircleOrText;

    /**
     * Gets the value of the squareOrCircleOrText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the squareOrCircleOrText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSquareOrCircleOrText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSquare }
     * {@link TCircle }
     * {@link TText }
     * 
     * 
     */
    public List<Object> getSquareOrCircleOrText() {
        if (squareOrCircleOrText == null) {
            squareOrCircleOrText = new ArrayList<Object>();
        }
        return this.squareOrCircleOrText;
    }

}
