//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 08:45:19 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://task_b.jd02_10.smirnov.it.by/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.smirnov.jd02_10.task_b.pojo_class;
