//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 01:00:48 AM MSK 
//


package by.it.Zyryanov.jd02_09.homework.bookpackage2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Books complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Books">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Book_title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Genre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Book_Cover">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://homework.jd02_09.Zyryanov.it.by}Book_Cover"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pages" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Books", propOrder = {
    "description",
    "publisher",
    "author",
    "bookTitle",
    "genre",
    "bookCover",
    "pages",
    "price"
})
public class Book {

    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Publisher", required = true)
    protected String publisher;
    @XmlElement(name = "Author", required = true)
    protected String author;
    @XmlElement(name = "Book_title", required = true)
    protected String bookTitle;
    @XmlElement(name = "Genre", required = true)
    protected String genre;
    @XmlElement(name = "Book_Cover", required = true)
    protected Book.BookCover bookCover;
    @XmlElement(name = "Pages", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger pages;
    @XmlElement(name = "Price", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger price;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublisher(String value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the bookTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookTitle() {
        return bookTitle;
    }

    /**
     * Sets the value of the bookTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookTitle(String value) {
        this.bookTitle = value;
    }

    /**
     * Gets the value of the genre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenre() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenre(String value) {
        this.genre = value;
    }

    /**
     * Gets the value of the bookCover property.
     * 
     * @return
     *     possible object is
     *     {@link Book.BookCover }
     *     
     */
    public Book.BookCover getBookCover() {
        return bookCover;
    }

    /**
     * Sets the value of the bookCover property.
     * 
     * @param value
     *     allowed object is
     *     {@link Book.BookCover }
     *     
     */
    public void setBookCover(Book.BookCover value) {
        this.bookCover = value;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPages(BigInteger value) {
        this.pages = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrice(BigInteger value) {
        this.price = value;
    }

    @Override
    public String toString() {
        return " Books { " +
                "\n description = '" + description + '\'' +
                "\n publisher = '" + publisher + '\'' +
                "\n author = '" + author + '\'' +
                "\n bookTitle = '" + bookTitle + '\'' +
                "\n genre = '" + genre + '\'' +
                "\n bookCover = '" + bookCover +  '\'' +
                "\n pages = '" + pages +  '\'' +
                "\n price = '" + price +  '\'' +
                "\n"+'}';
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://homework.jd02_09.Zyryanov.it.by}Book_Cover"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BookCover {

        @XmlAttribute(name = "Rigid")
        protected String rigid;
        @XmlAttribute(name = "Soft")
        protected String soft;
        @XmlAttribute(name = "Paper")
        protected String paper;
        @XmlAttribute(name = "Rubber")
        protected String rubber;

        /**
         * Gets the value of the rigid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRigid() {
            return rigid;
        }

        /**
         * Sets the value of the rigid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRigid(String value) {
            this.rigid = value;
        }

        /**
         * Gets the value of the soft property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSoft() {
            return soft;
        }

        /**
         * Sets the value of the soft property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSoft(String value) {
            this.soft = value;
        }

        /**
         * Gets the value of the paper property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaper() {
            return paper;
        }

        /**
         * Sets the value of the paper property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaper(String value) {
            this.paper = value;
        }

        /**
         * Gets the value of the rubber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRubber() {
            return rubber;
        }

        /**
         * Sets the value of the rubber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRubber(String value) {
            this.rubber = value;
        }

        @Override
        public String toString() {
            return "BookCover{" +
                    "\n rigid = '" + rigid + '\'' +
                    "\n soft = '" + soft + '\'' +
                    "\n paper = '" + paper + '\'' +
                    "\n rubber = '" + rubber + '\'' +
                    "\n" + '}';
        }
    }
}
