//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 01:00:48 AM MSK 
//


package by.it.Zyryanov.jd02_09.homework.bookpackage2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Book_Catalogue" type="{http://homework.jd02_09.Zyryanov.it.by}Book_Catalogue"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "BookShop")
public class BookShop {

    @XmlElement(name = "Book_Catalogue", required = true)
    protected BookCatalogue bookCatalogue;

    /**
     * Gets the value of the bookCatalogue property.
     * 
     * @return
     *     possible object is
     *     {@link BookCatalogue }
     *     
     */
    public BookCatalogue getBookCatalogue() {
        return bookCatalogue;
    }

    /**
     * Sets the value of the bookCatalogue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookCatalogue }
     *     
     */
    public void setBookCatalogue(BookCatalogue value) {
        this.bookCatalogue = value;
    }

    @Override
    public String toString() {
        return "BookShop { " +
                "\n bookCatalogue = " + bookCatalogue +
                "\n" + '}';
    }
}
