//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 01:00:48 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bookpackage2.homework.jd02_09.Zyryanov.it.by", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.Zyryanov.jd02_09.homework.bookpackage2;
