//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.23 at 05:45:26 PM MSK 
//


package by.it.korzun.jd02_10;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Brigade complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Brigade">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pilots" type="{http://jd02_10.korzun.it.by/}Pilots"/>
 *         &lt;element name="Navigator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Radio-operator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Stewardess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Brigade", propOrder = {
    "pilots",
    "navigator",
    "radioOperator",
    "stewardess"
})
public class Brigade {

    @XmlElement(name = "Pilots", required = true)
    protected Pilots pilots;
    @XmlElement(name = "Navigator", required = true)
    protected String navigator;
    @XmlElement(name = "Radio-operator", required = true)
    protected String radioOperator;
    @XmlElement(name = "Stewardess", required = true)
    protected String stewardess;

    /**
     * Gets the value of the pilots property.
     * 
     * @return
     *     possible object is
     *     {@link Pilots }
     *     
     */
    public Pilots getPilots() {
        return pilots;
    }

    /**
     * Sets the value of the pilots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pilots }
     *     
     */
    public void setPilots(Pilots value) {
        this.pilots = value;
    }

    /**
     * Gets the value of the navigator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavigator() {
        return navigator;
    }

    /**
     * Sets the value of the navigator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavigator(String value) {
        this.navigator = value;
    }

    /**
     * Gets the value of the radioOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadioOperator() {
        return radioOperator;
    }

    /**
     * Sets the value of the radioOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadioOperator(String value) {
        this.radioOperator = value;
    }

    /**
     * Gets the value of the stewardess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStewardess() {
        return stewardess;
    }

    /**
     * Sets the value of the stewardess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStewardess(String value) {
        this.stewardess = value;
    }

    @Override
    public String toString() {
        return "Brigade{" +
                "pilots=" + pilots +
                ", navigator='" + navigator + '\'' +
                ", radioOperator='" + radioOperator + '\'' +
                ", stewardess='" + stewardess + '\'' +
                '}';
    }
}
