//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 03:21:10 PM MSK 
//


package by.it.loktev.jd02_10;

import by.it.loktev.jd02_09.Square;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="square" type="{http://jd02_09.loktev.it.by}Square"/>
 *         &lt;element name="circle" type="{http://jd02_09.loktev.it.by}Circle"/>
 *         &lt;element name="text" type="{http://jd02_09.loktev.it.by}Text"/>
 *         &lt;element name="group" type="{http://jd02_09.loktev.it.by}Group"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "squareOrCircleOrText"
})
@XmlRootElement(name = "picture")
public class Picture {

    @XmlElements({
        @XmlElement(name = "square", type = by.it.loktev.jd02_09.Square.class),
        @XmlElement(name = "circle", type = Circle.class),
        @XmlElement(name = "text", type = Text.class),
        @XmlElement(name = "group", type = Group.class)
    })
    protected List<Object> squareOrCircleOrText;

    public Picture() {
        squareOrCircleOrText = new ArrayList<Object>();
    }

    /**
     * Gets the value of the squareOrCircleOrText property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the squareOrCircleOrText property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSquareOrCircleOrText().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Square }
     * {@link Circle }
     * {@link Text }
     * {@link Group }
     * 
     * 
     */
    public List<Object> getSquareOrCircleOrText() {
        if (squareOrCircleOrText == null) {
            squareOrCircleOrText = new ArrayList<Object>();
        }
        return this.squareOrCircleOrText;
    }

    @Override
    public String toString() {
        StringBuilder sb=new StringBuilder();
        sb.append("Picture");
        sb.append("\n(");
        for ( Object O : squareOrCircleOrText ) {
            if ( O instanceof Group )
                sb.append(((Group)O).toString("  "));
            else
                sb.append("\n  "+O.toString());
        }
        sb.append("\n)");
        return sb.toString();
    }

}
